// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieve_chirps.sql

package database

import (
	"context"
)

const retrieveChirps = `-- name: RetrieveChirps :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
ORDER BY created_at ASC
`

func (q *Queries) RetrieveChirps(ctx context.Context) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, retrieveChirps)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
